gradle-nexus/publish-plugin

.gitignore
'build' pattern in .gitignore would exclude build folders in all the subfolders.
It might cause unexpected exclusion of files under packages
like io.github.gradlenexus.build...
=> Fix .gitignore: build -> /build

build.gradle.kts, src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/CloseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/InitializeNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExceptions.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/ReleaseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/RetryingConfig.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/StagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/ActionRetrier.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/BasicActionRetrier.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/NexusClient.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitionerTest.kt
his PR adds retrying on the close and release requests. It is required as Nexus only acknowledge that a given repository has been accepted for transition. With Sonatype Nexus is can take minutes to finish the operation.
I started with a basic external [retrier](https://github.com/alexo/retrier), but separated it to be able to switch to some other (external or in-house implementation if needed or desired).
I also considered this [retrier](https://github.com/ravichaturvedi/retrier) (it seems to only support throwing exceptions to indicate a not successful attempt) and that one for [kotlin](https://github.com/michaelbull/kotlin-retry) (it uses suspended function and I'm not sure how Gradle deals with that in the plugins and in addition it is not in Maven Central nor jCenter). In GNSP, I have …
=> [#7] Configurable retries to close/release requests

.github/workflows/e2e.yml, .gitmodules, build.gradle.kts, src/compatTest/kotlin/io/github/gradlenexus/publishplugin/BaseGradleTest.kt, src/e2eTest/kotlin/io/github/gradlenexus/publishplugin/e2e/NexusPublishE2ETests.kt
I finally sat down and finished E2E testing with Sonatype Nexus (TestKit is lightly different in behaviors than nebula-test which I used before). There is are artifacts of the [minimal project published to Nexus](https://github.com/gradle-nexus-e2e/nexus-publish-e2e-minimal), the repository is closed and released. It can detect some regressions in the communications with Nexus (or occasionally fail on timeout ;-) ).
There is a [dedicated flow](https://github.com/gradle-nexus/publish-plugin/actions/runs/106832486) in GitHub Actions which executes "unit" and e2e tests (without the Gradle version compatibility tests). I needed to script it slightly, maybe it can be done easier in GH Actions.
The flow on the Sonatype side is constructed that way that on the staging repository close the …
=> E2E tests with Sonatype Nexus

.github/workflows/e2e.yml, build.gradle.kts
To do not display their values with --info (as parameters passed to
Gradle executor. Properties with "." cannot be passed that way.
They should be avoided on a CI server.
=> [#5] Prefer envVars when passing properties to E2E test

build.gradle.kts, src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractNexusStagingRepositoryTask.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/CloseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/InitializeNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/ReleaseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/NexusClient.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitionerTest.kt
The description can now be customized on the extension or individual
tasks and now defaults to the GAV of the root project.
In addition, the User-Agent (which is shown in Nexus UI) is now
customized to `gradle-nexus-publish-plugin/<version>`.
Resolves #31.
=> Make staging repo description configurable

.github/workflows/e2e.yml, build.gradle.kts, src/e2eTest/kotlin/io/github/gradlenexus/publishplugin/e2e/NexusPublishE2ETests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/TaskOrchestrationTest.kt
This PR adds the following tasks:
- `closeAndReleaseRepoNameStagingRepository` - for every Nexus repo configured
- `closeAndReleaseStagingRepository` - for projects with just one Nexus repo configured
-  `closeAndReleaseRepository` - deprecated (legacy) task similar to above intended to make migration from GNSP easier.
Fixed #33.
I also slightly reduced verbosity of E2E tests on a CI server .
=> [#33] closeAndRelease* simplified tasks

.github/workflows/e2e.yml, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/TaskOrchestrationTest.kt
As suggested in #38:
- depend on all `closeAndRelease*StagingRepository` tasks
As a bonus:
- display release task descriptions on `gw tasks`
Closes #38.
=> Improve simplified closeAndRelease task

build.gradle.kts
To use the latest okhttp. However, 45minus timeout on init repo still occurs with that version as well.
=> Bump retrofit and failsafe versions

src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/e2eTest/kotlin/io/github/gradlenexus/publishplugin/e2e/NexusPublishE2ETests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/RetryingConfig.kt
Joel from Sonatype recommended 5 minutes as a value that usually should be enough (currently it is ~15 seconds to initialize).
I also reduced verbosity of the E2E tests. Especially the multi-project build was very verbose due to the configuration in Kotlin (and related artifacts downloading and generation warnings).
Along the way a description of the staging repository generated from the CI server allows to track the build (to make it easier to find stale, undeleted repositories in Nexus).
=> Increase default client timeout to 5 minutes

.github/workflows/e2e.yml
To detect potential repressions/problems on the Sonatype side.
Based on the [documentation](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule). I haven't tested it.
Closes #43.
=> Run E2E tests once a week on CI server

src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractTransitionNexusStagingRepositoryTask.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/CloseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExceptions.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/ReleaseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/TransitionCheckOptions.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/BasicActionRetrier.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/NexusClient.kt
To avoid confusion since publishing is not retried, only checking the
repo's status when transitioning `RetryingConfig` is moved from
`NexusRepository` to `NexusPublishExtension` and renamed to
`TransitionCheckOptions`. The options specified in the extension are by
default applied to all close and release tasks but can be overridden on
each task, if need be.
Resolves #20.
=> Move retrying config from repo to extension and rename

src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/KotlinParameterizeTest.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/TaskOrchestrationTest.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitionerTest.kt
Not just "after evaluate" and also when no Nexus repositories are configured. This makes it easier to hide by power users.
Also removed compatibility method for Gradle 4.x which is not supported anymore and improved task orchestration tests.
@vlsi Does it match your needs?
Fixes #51.
=> Make closeAndReleaseStagingRepository always available

README.md, src/compatTest/kotlin/io/github/gradlenexus/publishplugin/MethodScopeWiremockResolver.kt, src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/RetrieveStagingProfile.kt
Closes #60 
I think we should add an update to the "Tasks" section of the migration guide to say something like 
```bash
./gradlew getStagingProfile
```
↓
```bash
./gradlew retrieveSonatypeStagingProfile
```
This reflects the main difference between the previous plugin project and this one: tasks are on a per `NexusRepsitory` basis, including the `RetrieveStagingProfile` task. 
First adds a new `AbstractNexusStagingRepositoryTask` subclass called `RetrieveStagingProfile`. we register a new `RetrieveStagingProfile` task for each `NexusRepository` registered in the plugin's extension. This enables users to run 
`./gradlew retrieve<NEXUS_REPOSITORY_NAME>StagingProfile` and see the staging profile ID for the repository in stdout. 
~This was initially as far as I was planning on going with …
=> ✨ Get staging profile task

src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/NexusClient.kt
Fixes https://github.com/gradle-nexus/publish-plugin/issues/91
This PR logs the (error) response body in the Exception thrown by the plugin whenever a HTTP response fails. This allows the user to fix the problem indicated by the Nexus server.
=> Display HTTP error response to the user

README.md
=> Fix Sonatype news link in README

build.gradle.kts
Due to JCenter shut down:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
To be merged after 1.0.0.
=> Limit JCenter to dokka and its dependencies

README.md
With a link to my old blog post explaining how to generate it.
https://blog.solidsoft.pl/2015/09/08/deploy-to-maven-central-using-api-key-aka-auth-token/
=> Recommend using user token instead of regular credentials

build.gradle.kts
No longer generate Javadoc using Dokka since it keeps causing issues and
we only have a single production class with Javadoc anyway.
=> Remove Dokka

README.md
These were steps I needed to do to get my publishing to work.
=> Added some more setup instructions to the README

build.gradle.kts
E.g. generated sources in nexus-publish-e2e-multi-project/buildSrc/
=> Exclude generated Kotlin sources from spotless valdration

src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt
As suggested in https://github.com/gradle-nexus/publish-plugin/issues/155. @nedtwigg is the new message more helpful in your opinion? Or you would tweak it even more?
Fixes #155.
=> [#155] Mention common reason of "not in desired state" error

.github/workflows/e2e.yml, .github/workflows/gradle-wrapper-validation.yml, .github/workflows/java-versions.yml, .github/workflows/main.yml
Note: images are clickable and they go to the corresponding GitHub Action Job.
| Workflow | Before | After |
| - | - | - |
| e2e.yml | [![image](https://user-images.githubusercontent.com/2906988/219330987-90b834ee-d1f0-4458-860e-752005a88d57.png)](https://github.com/gradle-nexus/publish-plugin/actions/runs/4167940358) |  Can't run, because it needs secrets, but considering the other successes, and that the same changes were made, I'm confident it'll work. 🤞 |
| gradle-wrapper-validation.yml | [![image](https://user-images.githubusercontent.com/2906988/219329935-89463839-e2ed-4e59-8a3c-cf9e17608c71.png)](https://github.com/gradle-nexus/publish-plugin/actions/runs/4192527426) | [![image](https://user-images.githubusercontent.com/2906988/219330061-d8a849e3-8620-494a-b087-06142dbbb6c6.png)](ht …
=> Bump all major versions of GitHub actions

src/compatTest/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPluginTests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt
Re-PR of https://github.com/TWiStErRob/nexus-publish-gradle-plugin/pull/5
Fixes #152 
Closes #160
Closes #165
=> Workaround #152 use ConfigureUtil only when it's not nagging

.editorconfig, .github/workflows/gradle-latest-versions.yml, .github/workflows/main.yml
To faster detect regressions, deprecations and incompatibilities. Simple variant to get started.
Closes #173.
=> Cron tests with latest Gradle version(s) on CI

.github/workflows/java-versions.yml
With Gradle 8.0 instead of 6.x, it is possible.
=> Test basic Java 17 compatibility on CI

.github/workflows/e2e.yml
To do not overuse Sonatype Nexus.
A simple version (without parsing the commit message). A manual execution could be used to trigger E2E tests also for other branches. WDYT?
Closes #181.
=> [#181] Limit E2E test execution

renovate.json
To prevent:
Renovate failed to look up the following dependencies: publishing:maven.
=> Exclude bogus dependency found by Renovate

build.gradle.kts
Remove workaround for https://github.com/gradle/gradle/issues/23928
https://plugins.gradle.org/plugin/com.gradle.plugin-publish has a new version 1.2.0
cc @vlsi
=> Update com.gradle.plugin-publish to 1.2.0 and remove workaround

.github/workflows/java-versions.yml
Build with JDK 8 will not be officially supported in 2.0.0. Although, it is still planned to have target set to JDK 8.
It also slightly speed up CI build (or at least decrease the load we generate).
=> [#171] Remove JDK 8 build on CI

src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractNexusStagingRepositoryTask.kt
Contributes to https://github.com/gradle-nexus/publish-plugin/issues/221, but doesn't not fully fix it.
All problems were rooted in this one common place, a captured `extension` object.
<details><summary>Evidence that all warnings are involved</summary>
From configuration-cache report posted here: https://github.com/gradle-nexus/publish-plugin/issues/221#issuecomment-1550964355
</details>
=> Fix most of configuration cache warnings

build.gradle.kts, src/e2eTest/kotlin/io/github/gradlenexus/publishplugin/e2e/NexusPublishE2ETests.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/NexusClient.kt
Closes #202
Same as #202, but with "breaking changes" accounted for.
=> chore(deps): update plugin com.diffplug.spotless to v6.19.0

.github/workflows/gradle-latest-versions.yml
To make it easier to find our why the regression tests fail.
=> Enable Gradle build scan for tests with latest Gradle version

README.md
Prior versions gave me this error:
> Cannot create a Publication named 'pom' because this container does not support creating elements by name alone. Please specify which subtype of Publication to create. Known subtypes are: MavenPublication
=> Fix sample gradle files

src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractNexusStagingRepositoryTask.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractTransitionNexusStagingRepositoryTask.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/InitializeNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/TransitionCheckOptions.kt
IDE identified these - I'm guessing they were originally added when kotlin-dsl was new.
=> Remove redundant suppressions

src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractNexusStagingRepositoryTask.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/AbstractTransitionNexusStagingRepositoryTask.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/CloseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/FindStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/InitializeNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/ReleaseNexusStagingRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/RetrieveStagingProfile.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/TransitionCheckOptions.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/TaskOrchestrationTest.kt
The main changes are:
1. Use managed properties, where possible
2. Avoid passing instances of `Project` around
3. Use the plugin to set default values in tasks and the extension
Parts 1 & 3 are not fully completed but I didn't want to press on if this wasn't desired. This should be safe to merge as is though as compat tests for Gradle 6 on Java 11 pass locally.
=> Partially refactor to use more idiomatic Gradle

build.gradle.kts, gradle.properties, src/compatTest/kotlin/io/github/gradlenexus/publishplugin/TestExtensions.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt
Please squash when merging.
Fixes #228 by not running two Gradle tests of the same version.
See [performance impact](https://github.com/gradle-nexus/publish-plugin/issues/228#issuecomment-1634091691) (positive, at least on my machine 😅) in the related issue.
`org.gradle.parallel` parallelizes tasks between projects.
`org.gradle.configuration-cache` parallelizes tasks inside projects.
`maxParallelForks` parallelizes Test classes inside Test tasks.
This PR
* reduces maxParallelForks to 1 so that `compatTestSomeGradleVersion` cannot run two tests which have the same Gradle needs at the same time.
* enables configuration cache so that `compatTestGradle1` and `compatTestGradle2` can run in parallel.
* Migrated from direct task access to newer APIs in KGP to prevent this warning:
```
> Task …
```
=> Fix #228: reduce parallelism in task and increase parallelism between tasks

src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusRepository.kt
Triggered by https://gradle-community.slack.com/archives/CA745PZHN/p1689848485387419
=> Remove non-required @Inject constructors.

build.gradle.kts, settings.gradle.kts
This allows naming the rootProject whatever we want. Improving developer experience in IDE for example.
**Before**:
**After**:
**Testing**: after this PR the binaries produced by `publishToMavenLocal` are exactly the same.
---
Note: by default this changes the Kotlin-mangled `internal` names:
but it's possible to set it https://github.com/gradle-nexus/publish-plugin/commit/2b2013eaa440e207846710390c3c3fac52d3c6a0
=> Make the artifact ID explicit rather than relying on implicit naming.

build.gradle.kts, src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/NexusRepository.kt, src/main/kotlin/io/github/gradlenexus/publishplugin/internal/StagingRepositoryTransitioner.kt, src/test/kotlin/io/github/gradlenexus/publishplugin/TaskOrchestrationTest.kt
Using the `kotlin-dsl` plugin creates additional implicit dependencies on the Kotlin version used by Gradle as seen in https://github.com/gradle-nexus/publish-plugin/pull/258#issue-1820712729.
Removing the use of kotlin-dsl in the plugin itself removes that dependency. Now the Kotlin version required by the project can be set independently and is not tied to the Kotlin version used by the Gradle version applied to the wrapper.
=> Drop kotlin-dsl plugin

README.md
Target compatibility is still set to 8, but it might change in the future, if needed.
Closes #171.
=> Mention JDK <11 support deprecation in README

build.gradle.kts
It can happen when executing e2e tests from cron on CI:
> Task :e2eTest FROM-CACHE
E.g. https://github.com/gradle-nexus/publish-plugin/actions/runs/7780393684/job/21213013841#step:6:34
=> Do not cache E2E tests

build.gradle.kts
Simplify the build file a bit by updating the way Kotlin API & language versions are declared, and how the JVM target is set.
=> Simplify build file

README.md
With the sunset of OSSRH and the migration to central, I found out not clear that one need to actually generate new central token as well, i.e. the previous OSSRH generated credentials (from nexus) won't work (results in `401 Unauthorized`)
* https://central.sonatype.org/news/20250326_ossrh_sunset/
* #377
This PR just put more weight on this point.
=> Legacy OSSRH tokens are incompatible with the new central portal
